### ISSUE TITLE
More BoatUtils Options 

### ISSUE THREAD

**Issue by LapisLettuce** [Makkuusen/TimingSystem#253]
Right now the popular ways to use BU on boat tracks is ir and r.

The BA version treats going downhill like packed ice
The IBWRC version treats everything like packed ice

Would be nice to add maybe a "js" and "s" option so that:
With the BA style, going downhill is like blue ice
With the IBWRC style, everything is treated like blue ice

These two options will either have to be exclusive or one overrides the other.

Should be able to just have everyone install a new BU mod for 1.20 because the tracks that switch to the new options would simply become faster. There would be no advantage for people to stay in the current 420.69 version.

**Comment by Makkuusen** [comment]
I'm pretty sure the current mod actually would include the possibility to have IBRWRC style, where everything is regarded as blue ice. So that could be integrated as an option in TimingSystem. The reason it isn't I guess is because I haven't heard anyone talk or ask about a blue race rally version for a long time.

However the desired BA style with blue ice fall speed would as you mention require a new version of BoatUtils. If that were to be developed, I'm pretty sure everyone would need to get a new boatutils for the tracks with these new option to be drivable.

But I guess the desire for a new BoatUtils probably needs to go in BoatLabs support on discord or straight to the developer.

**Comment by Makkuusen** [comment]
Fixed in OpenBoatUtils
