### ISSUE TITLE
Set track owner to any playername

### ISSUE THREAD

**Issue by Adamsapplespie** [Makkuusen/TimingSystem#262]
Currently track owners can only be set to a player who has previously joined the server. Can this be changed to also allow track owners to be indicated as any name you input? 

A benefit is that you don't need to pester the creator of a track to join your server for getting their credits on a given map

**Comment by Pigalala** [comment]
It is possible that this feature could be abused in some way that we wouldn't want. For now, this will not be implemented as it remove player name updating and would potentially break any future plans (such as #295) where it is important that the player has joined the server before.

**Comment by Adamsapplespie** [comment]
Bruh how would this be an exploitable feature? At least couldn't we set the track owner to a given UUID? That way it could still update

**Comment by Makkuusen** [comment]
@Pigalala So I agree we would not want to change the database to store plain text instead of uuids, and that every uuid has to exists in the players table.

The option to make this happen would be to allow /t set owner <track> <uuid> and if the uuid doesn't already exist in the database you send an api request to mojangs servers to retrieve the username. Then you make a new entry into the player database with the name and the uuid. https://wiki.vg/Mojang_API

The limitation is that the playername will never be updated without the player joining the server. But because there are limitations on the mojang api I don't think we wanna implement any updates.

But ofc there is some work behind this to implement and test.
