### ISSUE TITLE
/t info <track> <player> Permission node

### ISSUE THREAD

**Issue by SethTheLasersloth** [Makkuusen/TimingSystem#269]
Hey!
We were wondering if it'd be possible to allow the `/t info <track> <player>` command to be given to non-opped users. Like, a permission node would be great for it.
Or is there a specific reason why this is an op-only feature? (Or, actually, is it even op-only? Staff in Frosthex have the track.admin permission, but they cannot do the command, which is why I ask...)

**Comment by JustBru00** [comment]
Makkuusen/TimingSystem#269

**Comment by Makkuusen** [comment]
So this ties into how we want player data to be displayed.

Data like how much time an individual person has spent on a certain track is by default hidden even for track.admins as this for some individuals could be considered sensitive data. Some people would prefer this data to be private, as it could be used with bad intent.

A scenario as follows could be. 

"Lapis spent 15 hours on this track and I beat him in only 15 minutes. Lul get rekt im better than him"

It might not be in Lapis interest to share this data. And if that is the case I think it would be cool to give Lapis the choice for his data to be private or not.

As you can tell, this information is already available to op's, so it is not like the current implementation fully prevents this scenario and I'm the first to admit that I'm probably one of the worst offenders at looking into people's data.

My idea for timing system would probably be to make changes that let people make decisions about their personal data, rather than giving it out to more people. This could be applied for time spent, attempts, finishes, checkpoint timers and such.

However, one useful thing and a reason for admins to access this data would be in terms of detecting cheaters.

I'm still a bit conflicted about this issue, but writing to let everyone know my thinking about this. Feel free to provide your own input.

**Comment by JustBru00** [comment]
Can we not just add a `track.operator` permission node?
Staff need to be able to review times to catch cheating players.
